
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_commande?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    # username: guest (par défaut)
    # password: guest (par défaut)
