server:
  port: 8080

# Configuration Eureka
eureka:
  client:
    # On lui dit de s'enregistrer auprès d'Eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Préfère utiliser l'IP pour s'enregistrer
    prefer-ip-address: true

# Configuration de la SÉCURITÉ (Google OAuth2)
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # -----------------------------------------------------------------
            # À REMPLIR : Allez sur console.cloud.google.com pour les obtenir
            client-id: "1082771493964-f87gdrrsin26mhjujoeacaglsag55m42.apps.googleusercontent.com"
            client-secret: "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"
            # -----------------------------------------------------------------

  cloud:
    gateway:
      # Configuration des ROUTES
      routes:
        # 1. Microservice Produit
        - id: produit-service
          uri: lb://PRODUIT-SERVICE # "lb" signifie "Load Balanced" via Eureka
          predicates:
            - Path=/api/produits/**, /api/categories/**

        # 2. Microservice Client
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/clients/**

        # 3. Microservice Commande
        - id: commande-service
          uri: lb://COMMANDE-SERVICE
          predicates:
            - Path=/api/commandes/**

        # 4. Microservice Paiement
        - id: paiement-service
          uri: lb://PAIEMENT-SERVICE
          predicates:
            - Path=/api/paiements/**

      # Configuration de la validation des Tokens
      default-filters:
        - TokenRelay

# Activer la sécurité sur toutes les routes
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
