server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_produit?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: "" # Mettez votre mot de passe si vous en avez un
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
